[heading]
#Special parsing functions
#has_key=[list,of,things] = has any of the listed items in the card[key] property
#is_key=[list,of,things] = has all of the listed items in the card[key] property with no extras
#not_key=[list,of,things] = has none of the listed items in the card[key] property
#len_key=0 = length of str(card[key]) is equal to this
#len_key_lt=0 = length of str(card[key]) is less than this
#len_key_gt=0 = length of str(card[key]) is greater than this
#regex_key = regex pattern matches card[key]

[symbology]
"{W}"="ow"
"{U}"="ou"
"{B}"="ob"
"{R}"="or"
"{G}"="og"

[fonts]
GoudyMediaevalDemiBold="_fonts/GoudyMediaevalDemiBold.ttf"
GoudyMediaevalRegular="_fonts/GoudyMediaevalRegular.ttf"
GoudyMedievalAlternate="_fonts/GoudyMedievalAlternate.ttf"
NDPMTG="_fonts/NDPMTG.ttf"
PlantinMTProBold="_fonts/PlantinMTProBold.TTF"
PlantinMTProBoldIt="_fonts/PlantinMTProBoldIt.TTF"
PlantinMTProCnBd="_fonts/PlantinMTProCnBd.TTF"
PlantinMTProLight="_fonts/PlantinMTProLight.TTF"
PlantinMTProLightIt="_fonts/PlantinMTProLightIt.TTF"
PlantinMTProRg="_fonts/PlantinMTProRg.TTF"
PlantinMTProRgIt="_fonts/PlantinMTProRgIt.TTF"
PlantinMTProSemiBdIt="_fonts/PlantinMTProSemiBdIt.TTF"
PlantinMTProSmBd="_fonts/PlantinMTProSmBd.TTF"

# ---- Frames ---- #
[layers]
[layers.borders]
[layers.borders.black]
[layers.borders.white]
[layers.borders.silver]
[layers.borders.gold]

[layers.frame.standard]
conditions={"not_type"=["land","planeswalker","artifact","token"]}

# Single Color
[layers.frame.standard.w]
conditions={"has_colors"=["w"],"len_colors_lt"=3,"not_colors"=["r","g"]}
image="standard/w.png"
[layers.frame.standard.u]
conditions={"has_colors"=["u"],"len_colors_lt"=3,"not_colors"=["w","g"]}
image="standard/u.png"
[layers.frame.standard.b]
conditions={"has_colors"=["b"],"len_colors_lt"=3,"not_colors"=["w","u"]}
image="standard/b.png"
[layers.frame.standard.r]
conditions={"has_colors"=["r"],"len_colors_lt"=3,"not_colors"=["u","b"]}
image="standard/r.png"
[layers.frame.standard.g]
conditions={"has_colors"=["g"],"len_colors_lt"=3,"not_colors"=["b","r"]}
image="standard/g.png"

# Dual-Colors
[layers.frame.standard._w]
conditions={"has_colors"=["r","g","w"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[rg]/[w]\\}.*$/i"]}
image="standard/_w.png"
[layers.frame.standard._u]
conditions={"has_colors"=["w","g","u"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[wg]/[u]\\}.*$/i"]}
image="standard/_u.png"
[layers.frame.standard._b]
conditions={"has_colors"=["w","u","b"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[wu]/[b]\\}.*$/i"]}
image="standard/_b.png"
[layers.frame.standard._r]
conditions={"has_colors"=["u","b","r"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[ub]/[r]\\}.*$/i"]}
image="standard/_r.png"
[layers.frame.standard._g]
conditions={"has_colors"=["b","r","g"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[br]/[g]\\}.*$/i"]}
image="standard/_g.png"

# Special Colors
[layers.frame.standard.m]
conditions={"len_colors_gt"=3}
[layers.frame.standard.c]
conditions={"not_colors"=["w","u","b","r","g"],"not_type"=["artifact"]}

# Text
[layers.text.standard.name]
x=352
y=246
font="GoudyMedievalAlternate"
size=10
height=147
align="left"

[layers.text.standard.mana_cost]
x=340
y=1848
font="NDPMTG"
size=8
height=109
align="right"

[layers.text.standard.type_line]
x=340
y=1848
font="PlantinMTProRg"
size=8
height=109
align="left"

[layers.text.standard.oracle_text]
x=365
y=2014.31
font="PlantinMTProRg"
size=7.5
height=861.69
align="left"

[layers.text.standard.oracle_text.reminder]
x=365
y=2014.31
font="PlantinMTProRgIt"
size=7.5
height=861.69
align="left"

[layers.text.standard.artist]
x=830.21
y=2899.97
font="PlantinMTProRg"
size=7
height=96.6
align="center"

[layers.text.standard.copyright]
x=830.21
y=2989.48
font="PlantinMTProRg"
size=6
height=96.6
align="center"

[layers.text.standard.copyright]
x=1967.13
y=2902.85
font="PlantinMTProRg"
size=6
height=150.08
width=181.5
align="right"

# ARTIFACT
[layers.frame.artifact]
conditions={"has_type"=["artifact"],"not_type"=["land","token"]}

# Single Color
[layers.frame.artifact.w]
conditions={"has_colors"=["w"],"len_colors_lt"=3,"not_colors"=["r","g"]}
image="artifact/w.png"
[layers.frame.artifact.u]
conditions={"has_colors"=["u"],"len_colors_lt"=3,"not_colors"=["w","g"]}
image="artifact/u.png"
[layers.frame.artifact.b]
conditions={"has_colors"=["b"],"len_colors_lt"=3,"not_colors"=["w","u"]}
image="artifact/b.png"
[layers.frame.artifact.r]
conditions={"has_colors"=["r"],"len_colors_lt"=3,"not_colors"=["u","b"]}
image="artifact/r.png"
[layers.frame.artifact.g]
conditions={"has_colors"=["g"],"len_colors_lt"=3,"not_colors"=["b","r"]}
image="artifact/g.png"

# Dual-Colors
[layers.frame.artifact._w]
conditions={"has_colors"=["r","g","w"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[rg]/[w]\\}.*$/i"]}
image="artifact/_w.png"
[layers.frame.artifact._u]
conditions={"has_colors"=["w","g","u"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[wg]/[u]\\}.*$/i"]}
image="artifact/_u.png"
[layers.frame.artifact._b]
conditions={"has_colors"=["w","u","b"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[wu]/[b]\\}.*$/i"]}
image="artifact/_b.png"
[layers.frame.artifact._r]
conditions={"has_colors"=["u","b","r"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[ub]/[r]\\}.*$/i"]}
image="artifact/_r.png"
[layers.frame.artifact._g]
conditions={"has_colors"=["b","r","g"],"len_colors"=2,"regex_mana_cost"=["/^.*\\{[br]/[g]\\}.*$/i"]}
image="artifact/_g.png"

# Special Colors
[layers.frame.artifact.m]
conditions={"len_colors_gt"=3}
[layers.frame.artifact.c]
conditions={"not_colors"=["w","u","b","r","g"],"not_type"=["artifact"]}
