[layouts]
adventure = ["layout_has_adventure"]
aftermath = ["layout_has_split","oracle_text_has_aftermath"]
artifact = ["type_line_not_land", "type_line_has_artifact"]
#art_series = ["layout_has_art_series"]
augment = ["layout_has_augment"]
class = ["layout_has_class"]
#double_faced_token = ["layout_has_double_faced_token"]
emblem = ["layout_has_emblem"]
flip = ["layout_has_flip"]
fuse = ["layout_has_split","oracle_text_has_fuse"]
host = ["tayout_has_host"]
hybrid = ["mana_cost_regex_.*\\{[WUBRG]\\/[WUBRG]\\}.*"]
land = ["type_line_has_land","type_line_not_artifact"]
land_artifact = ["type_line_has_land", "type_line_has_artifact"]
leveler = ["layout_has_leveler"]
#meld = ["layout_has_meld"]
modal_dfc = ["layout_has_modal_dfc"]
normal = ["layout_has_normal"]
planar = ["layout_has_planar"]
#reversible_card = ["layout_has_reversible_card"]
saga = ["layout_has_saga"]
scheme = ["layout_has_scheme"]
split = ["layout_has_split","oracle_text_not_fuse", "oracle_text_not_aftermath"]
token = ["layout_has_token"]
transform = ["layout_has_transform"]
vanguard = ["layout_has_vanguard"]

[variants]
artifact = ["borderless", "extended", "fullart", "fulltext", "normal"]
land = ["borderless", "extended", "fullart", "fulltext", "normal"]
normal = ["borderless", "extended", "fullart", "fulltext", "normal"]

[decorations]
snow=[]
nyx=[]